import { NextResponse } from "next/server";
import { readFileSync } from "fs";
import { join } from "path";

/**
 * Serves amplify_outputs.json to the client at runtime.
 * The file is generated by `ampx sandbox` and is never committed to source control.
 * Returns 404 during CI builds where no sandbox is running.
 */
export function GET() {
  try {
    const outputsPath = join(process.cwd(), "..", "amplify_outputs.json");
    const contents = readFileSync(outputsPath, "utf-8");
    return NextResponse.json(JSON.parse(contents) as Record<string, unknown>);
  } catch {
    return NextResponse.json({ error: "amplify_outputs.json not found" }, { status: 404 });
  }
}
