/**
 * Amplify client configuration.
 * amplify_outputs.json is generated by `ampx sandbox` or `ampx generate outputs`.
 * It is gitignored — never commit it.
 * During CI builds without a sandbox, Amplify is not configured (auth calls will fail gracefully).
 */
import { Amplify } from "aws-amplify";

let configured = false;

export function configureAmplify() {
  if (configured) return;
  configured = true;

  if (typeof window === "undefined") return; // skip on server during static build

  fetch("/api/amplify-config")
    .then((r) => (r.ok ? r.json() : null))
    .then((outputs) => {
      if (outputs) Amplify.configure(outputs as Parameters<typeof Amplify.configure>[0], { ssr: true });
    })
    .catch(() => {
      if (process.env["NODE_ENV"] !== "test") {
        console.warn("Amplify outputs not available. Run `npx ampx sandbox` to generate them.");
      }
    });
}
